= Acknowledgements

This book would not be possible without the support and input from many individuals. I would like to thank everyone in the Angular, JavaScript and web development communities who not only shares knowledge and works on open source tools, but also advocates for inclusive communities and software.

Thanks to the teams at 9elements, Diebold Nixdorf and Keysight Technologies for the opportunity to work on first-class Angular applications. Thanks for the challenges, resources and patience that allowed me to research automated testing in detail.

Thanks to https://netbasal.com/[Netanel Basal] for valuable feedback on the book, for creating Spectator and for many helpful articles on Angular and testing.

Thanks to https://ichimnetz.com/[Nils Binder] for helping with the design, including the dark color scheme. Thanks to Melina Jacob for designing the e-book cover.

Thanks to https://timdeschryver.dev/[Tim Deschryver], https://kentcdodds.com/[Kent C. Dodds], https://twitter.com/karaforthewin[Kara Erickson], https://asim.dev/[Asim Hussain], https://twitter.com/ladyleet[Tracy Lee], https://brandonroberts.dev/[Brandon Roberts], https://jesselpalmer.com/[Jesse Palmer], Corinna Cohn, https://twitter.com/heathkit[Mike Giambalvo], https://twitter.com/cnishina[Craig Nishina], https://lucasfcosta.com/[Lucas F. Costa] and https://jess.sh/[Jessica Sachs] for insights on Angular, RxJS and automated testing.

