= Target audience

Learning objectives

- Angular topics you need to know when reading this book
- Where to learn about Angular core concepts
- Picking chapters you are interested in

The target audience of this guide are intermediate Angular developers. You should be familiar with Angular’s core concepts.

TIP: Testing, not implementation

This guide teaches you how to test Angular application parts like Components and Services. It assumes you know how to implement them, but not how to test them properly. If you have questions regarding Angular’s core concepts, please refer to the https://angular.io/docs[official Angular documentation].

If you have not used individual concepts yet, like Directives, that is fine. You can simply skip the related chapters and pick chapters you are interested in.

TIP: JavaScript & TypeScript proficiency

Furthermore, this guide is not an introduction to JavaScript or TypeScript. It assumes you have enough JavaScript and TypeScript knowledge to write the implementation and test code you need. Of course, this guide will explain special idioms commonly used for testing.

The official Angular documentation offers a comprehensive https://angular.io/guide/testing[guide on testing]. It is a recommended reading, but this guide does not assume you have read it.

